//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proba1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ед изм.
    /// </summary>
    // *** Start programmer edit section *** (ЕдИзм CustomAttributes)

    // *** End programmer edit section *** (ЕдИзм CustomAttributes)
    public enum ЕдИзм
    {
        
        /// <summary>
        /// Шт.
        /// </summary>
        // *** Start programmer edit section *** (ЕдИзм.Шт CustomAttributes)

        // *** End programmer edit section *** (ЕдИзм.Шт CustomAttributes)
        [Caption("Шт")]
        Шт,
        
        /// <summary>
        /// Тонн.
        /// </summary>
        // *** Start programmer edit section *** (ЕдИзм.Тонн CustomAttributes)

        // *** End programmer edit section *** (ЕдИзм.Тонн CustomAttributes)
        [Caption("Тонн")]
        Тонн,
        
        /// <summary>
        /// Кг.
        /// </summary>
        // *** Start programmer edit section *** (ЕдИзм.Кг CustomAttributes)

        // *** End programmer edit section *** (ЕдИзм.Кг CustomAttributes)
        [Caption("Кг")]
        Кг,
        
        /// <summary>
        /// Л.
        /// </summary>
        // *** Start programmer edit section *** (ЕдИзм.Л CustomAttributes)

        // *** End programmer edit section *** (ЕдИзм.Л CustomAttributes)
        [Caption("Л")]
        Л,
    }
}
