//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proba1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Клиенты.
    /// </summary>
    // *** Start programmer edit section *** (Клиенты CustomAttributes)

    // *** End programmer edit section *** (Клиенты CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлиентыE", new string[] {
            "НаимЗаказа as \'Наим заказа\'",
            "Телефон as \'Телефон\'",
            "АдресПоставщика as \'Адрес поставщика\'",
            "РасчетСчет as \'Расчет счет\'"})]
    [View("КлиентыL", new string[] {
            "НаимЗаказа as \'Наим заказа\'",
            "Телефон as \'Телефон\'",
            "АдресПоставщика as \'Адрес поставщика\'",
            "РасчетСчет as \'Расчет счет\'"})]
    public class Клиенты : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаимЗаказа;
        
        private int fТелефон;
        
        private string fАдресПоставщика;
        
        private int fРасчетСчет;
        
        // *** Start programmer edit section *** (Клиенты CustomMembers)

        // *** End programmer edit section *** (Клиенты CustomMembers)

        
        /// <summary>
        /// АдресПоставщика.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.АдресПоставщика CustomAttributes)

        // *** End programmer edit section *** (Клиенты.АдресПоставщика CustomAttributes)
        [StrLen(255)]
        public virtual string АдресПоставщика
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.АдресПоставщика Get start)

                // *** End programmer edit section *** (Клиенты.АдресПоставщика Get start)
                string result = this.fАдресПоставщика;
                // *** Start programmer edit section *** (Клиенты.АдресПоставщика Get end)

                // *** End programmer edit section *** (Клиенты.АдресПоставщика Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.АдресПоставщика Set start)

                // *** End programmer edit section *** (Клиенты.АдресПоставщика Set start)
                this.fАдресПоставщика = value;
                // *** Start programmer edit section *** (Клиенты.АдресПоставщика Set end)

                // *** End programmer edit section *** (Клиенты.АдресПоставщика Set end)
            }
        }
        
        /// <summary>
        /// НаимЗаказа.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.НаимЗаказа CustomAttributes)

        // *** End programmer edit section *** (Клиенты.НаимЗаказа CustomAttributes)
        [StrLen(255)]
        public virtual string НаимЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.НаимЗаказа Get start)

                // *** End programmer edit section *** (Клиенты.НаимЗаказа Get start)
                string result = this.fНаимЗаказа;
                // *** Start programmer edit section *** (Клиенты.НаимЗаказа Get end)

                // *** End programmer edit section *** (Клиенты.НаимЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.НаимЗаказа Set start)

                // *** End programmer edit section *** (Клиенты.НаимЗаказа Set start)
                this.fНаимЗаказа = value;
                // *** Start programmer edit section *** (Клиенты.НаимЗаказа Set end)

                // *** End programmer edit section *** (Клиенты.НаимЗаказа Set end)
            }
        }
        
        /// <summary>
        /// РасчетСчет.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.РасчетСчет CustomAttributes)

        // *** End programmer edit section *** (Клиенты.РасчетСчет CustomAttributes)
        public virtual int РасчетСчет
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.РасчетСчет Get start)

                // *** End programmer edit section *** (Клиенты.РасчетСчет Get start)
                int result = this.fРасчетСчет;
                // *** Start programmer edit section *** (Клиенты.РасчетСчет Get end)

                // *** End programmer edit section *** (Клиенты.РасчетСчет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.РасчетСчет Set start)

                // *** End programmer edit section *** (Клиенты.РасчетСчет Set start)
                this.fРасчетСчет = value;
                // *** Start programmer edit section *** (Клиенты.РасчетСчет Set end)

                // *** End programmer edit section *** (Клиенты.РасчетСчет Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.Телефон CustomAttributes)

        // *** End programmer edit section *** (Клиенты.Телефон CustomAttributes)
        public virtual int Телефон
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.Телефон Get start)

                // *** End programmer edit section *** (Клиенты.Телефон Get start)
                int result = this.fТелефон;
                // *** Start programmer edit section *** (Клиенты.Телефон Get end)

                // *** End programmer edit section *** (Клиенты.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.Телефон Set start)

                // *** End programmer edit section *** (Клиенты.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (Клиенты.Телефон Set end)

                // *** End programmer edit section *** (Клиенты.Телефон Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлиентыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентыE", typeof(IIS.Proba1.Клиенты));
                }
            }
            
            /// <summary>
            /// "КлиентыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентыL", typeof(IIS.Proba1.Клиенты));
                }
            }
        }
    }
}
