//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proba1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Удовл кл.
    /// </summary>
    // *** Start programmer edit section *** (УдовлКл CustomAttributes)

    // *** End programmer edit section *** (УдовлКл CustomAttributes)
    public enum УдовлКл
    {
        
        /// <summary>
        /// НеУдовл.
        /// </summary>
        // *** Start programmer edit section *** (УдовлКл.НеУдовл CustomAttributes)

        // *** End programmer edit section *** (УдовлКл.НеУдовл CustomAttributes)
        [Caption("НеУдовл")]
        НеУдовл,
        
        /// <summary>
        /// Удовл.
        /// </summary>
        // *** Start programmer edit section *** (УдовлКл.Удовл CustomAttributes)

        // *** End programmer edit section *** (УдовлКл.Удовл CustomAttributes)
        [Caption("Удовл")]
        Удовл,
    }
}
