//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proba1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Формир распр.
    /// </summary>
    // *** Start programmer edit section *** (ФормирРаспр CustomAttributes)

    // *** End programmer edit section *** (ФормирРаспр CustomAttributes)
    [AutoAltered()]
    [Caption("Формир распр")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ФормирРаспрE", new string[] {
            "Дата as \'Дата\'",
            "НомерДогРаспр as \'Номер дог распр\'",
            "СписокБарж as \'Список барж\'",
            "СписокБарж.Производитель as \'Производитель\'",
            "СписокКонтей as \'Список контей\'",
            "СписокКонтей.НаимКонтей as \'Наим контей\'",
            "ПунктПогрузки as \'Пункт погрузки\'",
            "ПунктПогрузки.Адрес as \'Адрес\'",
            "ДокумПостав as \'Докум постав\'",
            "ДокумПостав.Организация",
            "ДокумПостав.Организация.НаимОрганиз"}, Hidden=new string[] {
            "СписокБарж.Производитель",
            "СписокКонтей.НаимКонтей",
            "ПунктПогрузки.Адрес"})]
    [MasterViewDefineAttribute("ФормирРаспрE", "СписокБарж", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Производитель")]
    [MasterViewDefineAttribute("ФормирРаспрE", "СписокКонтей", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НаимКонтей")]
    [MasterViewDefineAttribute("ФормирРаспрE", "ПунктПогрузки", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Адрес")]
    [MasterViewDefineAttribute("ФормирРаспрE", "ДокумПостав", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Дата")]
    [View("ФормирРаспрL", new string[] {
            "Дата as \'Дата\'",
            "НомерДогРаспр as \'Номер дог распр\'",
            "СписокБарж.Производитель as \'Производитель\'",
            "СписокКонтей.НаимКонтей as \'Наим контей\'",
            "ПунктПогрузки.Адрес as \'Адрес\'",
            "ДокумПостав.Дата as \'Дата\'"})]
    public class ФормирРаспр : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private int fНомерДогРаспр;
        
        private IIS.Proba1.СписокБарж fСписокБарж;
        
        private IIS.Proba1.СписокКонтей fСписокКонтей;
        
        private IIS.Proba1.ПунктПогрузки fПунктПогрузки;
        
        private IIS.Proba1.ДокумПостав fДокумПостав;
        
        // *** Start programmer edit section *** (ФормирРаспр CustomMembers)

        // *** End programmer edit section *** (ФормирРаспр CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРаспр.Дата CustomAttributes)

        // *** End programmer edit section *** (ФормирРаспр.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРаспр.Дата Get start)

                // *** End programmer edit section *** (ФормирРаспр.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ФормирРаспр.Дата Get end)

                // *** End programmer edit section *** (ФормирРаспр.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРаспр.Дата Set start)

                // *** End programmer edit section *** (ФормирРаспр.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ФормирРаспр.Дата Set end)

                // *** End programmer edit section *** (ФормирРаспр.Дата Set end)
            }
        }
        
        /// <summary>
        /// НомерДогРаспр.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРаспр.НомерДогРаспр CustomAttributes)

        // *** End programmer edit section *** (ФормирРаспр.НомерДогРаспр CustomAttributes)
        public virtual int НомерДогРаспр
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРаспр.НомерДогРаспр Get start)

                // *** End programmer edit section *** (ФормирРаспр.НомерДогРаспр Get start)
                int result = this.fНомерДогРаспр;
                // *** Start programmer edit section *** (ФормирРаспр.НомерДогРаспр Get end)

                // *** End programmer edit section *** (ФормирРаспр.НомерДогРаспр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРаспр.НомерДогРаспр Set start)

                // *** End programmer edit section *** (ФормирРаспр.НомерДогРаспр Set start)
                this.fНомерДогРаспр = value;
                // *** Start programmer edit section *** (ФормирРаспр.НомерДогРаспр Set end)

                // *** End programmer edit section *** (ФормирРаспр.НомерДогРаспр Set end)
            }
        }
        
        /// <summary>
        /// Формир распр.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРаспр.ДокумПостав CustomAttributes)

        // *** End programmer edit section *** (ФормирРаспр.ДокумПостав CustomAttributes)
        [PropertyStorage(new string[] {
                "ДокумПостав"})]
        [NotNull()]
        public virtual IIS.Proba1.ДокумПостав ДокумПостав
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРаспр.ДокумПостав Get start)

                // *** End programmer edit section *** (ФормирРаспр.ДокумПостав Get start)
                IIS.Proba1.ДокумПостав result = this.fДокумПостав;
                // *** Start programmer edit section *** (ФормирРаспр.ДокумПостав Get end)

                // *** End programmer edit section *** (ФормирРаспр.ДокумПостав Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРаспр.ДокумПостав Set start)

                // *** End programmer edit section *** (ФормирРаспр.ДокумПостав Set start)
                this.fДокумПостав = value;
                // *** Start programmer edit section *** (ФормирРаспр.ДокумПостав Set end)

                // *** End programmer edit section *** (ФормирРаспр.ДокумПостав Set end)
            }
        }
        
        /// <summary>
        /// Формир распр.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРаспр.ПунктПогрузки CustomAttributes)

        // *** End programmer edit section *** (ФормирРаспр.ПунктПогрузки CustomAttributes)
        [PropertyStorage(new string[] {
                "ПунктПогрузки"})]
        [NotNull()]
        public virtual IIS.Proba1.ПунктПогрузки ПунктПогрузки
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРаспр.ПунктПогрузки Get start)

                // *** End programmer edit section *** (ФормирРаспр.ПунктПогрузки Get start)
                IIS.Proba1.ПунктПогрузки result = this.fПунктПогрузки;
                // *** Start programmer edit section *** (ФормирРаспр.ПунктПогрузки Get end)

                // *** End programmer edit section *** (ФормирРаспр.ПунктПогрузки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРаспр.ПунктПогрузки Set start)

                // *** End programmer edit section *** (ФормирРаспр.ПунктПогрузки Set start)
                this.fПунктПогрузки = value;
                // *** Start programmer edit section *** (ФормирРаспр.ПунктПогрузки Set end)

                // *** End programmer edit section *** (ФормирРаспр.ПунктПогрузки Set end)
            }
        }
        
        /// <summary>
        /// Формир распр.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРаспр.СписокБарж CustomAttributes)

        // *** End programmer edit section *** (ФормирРаспр.СписокБарж CustomAttributes)
        [PropertyStorage(new string[] {
                "СписокБарж"})]
        [NotNull()]
        public virtual IIS.Proba1.СписокБарж СписокБарж
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРаспр.СписокБарж Get start)

                // *** End programmer edit section *** (ФормирРаспр.СписокБарж Get start)
                IIS.Proba1.СписокБарж result = this.fСписокБарж;
                // *** Start programmer edit section *** (ФормирРаспр.СписокБарж Get end)

                // *** End programmer edit section *** (ФормирРаспр.СписокБарж Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРаспр.СписокБарж Set start)

                // *** End programmer edit section *** (ФормирРаспр.СписокБарж Set start)
                this.fСписокБарж = value;
                // *** Start programmer edit section *** (ФормирРаспр.СписокБарж Set end)

                // *** End programmer edit section *** (ФормирРаспр.СписокБарж Set end)
            }
        }
        
        /// <summary>
        /// Формир распр.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРаспр.СписокКонтей CustomAttributes)

        // *** End programmer edit section *** (ФормирРаспр.СписокКонтей CustomAttributes)
        [PropertyStorage(new string[] {
                "СписокКонтей"})]
        [NotNull()]
        public virtual IIS.Proba1.СписокКонтей СписокКонтей
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРаспр.СписокКонтей Get start)

                // *** End programmer edit section *** (ФормирРаспр.СписокКонтей Get start)
                IIS.Proba1.СписокКонтей result = this.fСписокКонтей;
                // *** Start programmer edit section *** (ФормирРаспр.СписокКонтей Get end)

                // *** End programmer edit section *** (ФормирРаспр.СписокКонтей Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРаспр.СписокКонтей Set start)

                // *** End programmer edit section *** (ФормирРаспр.СписокКонтей Set start)
                this.fСписокКонтей = value;
                // *** Start programmer edit section *** (ФормирРаспр.СписокКонтей Set end)

                // *** End programmer edit section *** (ФормирРаспр.СписокКонтей Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ФормирРаспрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормирРаспрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормирРаспрE", typeof(IIS.Proba1.ФормирРаспр));
                }
            }
            
            /// <summary>
            /// "ФормирРаспрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормирРаспрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормирРаспрL", typeof(IIS.Proba1.ФормирРаспр));
                }
            }
        }
    }
}
