//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proba1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Формир рез пос.
    /// </summary>
    // *** Start programmer edit section *** (ФормирРезПос CustomAttributes)

    // *** End programmer edit section *** (ФормирРезПос CustomAttributes)
    [AutoAltered()]
    [Caption("Формир рез пос")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ФормирРезПосE", new string[] {
            "Дата as \'Дата\'",
            "СтатусЗаказа as \'Статус заказа\'",
            "НаличДеф as \'Налич деф\'",
            "УдовлКл as \'Удовл кл\'",
            "ФормирРаспр as \'Формир распр\'",
            "ФормирРаспр.Дата as \'Дата\'"}, Hidden=new string[] {
            "ФормирРаспр.Дата"})]
    [MasterViewDefineAttribute("ФормирРезПосE", "ФормирРаспр", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Дата")]
    [View("ФормирРезПосL", new string[] {
            "Дата as \'Дата\'",
            "СтатусЗаказа as \'Статус заказа\'",
            "НаличДеф as \'Налич деф\'",
            "УдовлКл as \'Удовл кл\'",
            "ФормирРаспр.Дата as \'Дата\'"})]
    public class ФормирРезПос : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private IIS.Proba1.СтатусЗаказа fСтатусЗаказа;
        
        private bool fНаличДеф;
        
        private IIS.Proba1.УдовлКл fУдовлКл;
        
        private IIS.Proba1.ФормирРаспр fФормирРаспр;
        
        // *** Start programmer edit section *** (ФормирРезПос CustomMembers)

        // *** End programmer edit section *** (ФормирРезПос CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРезПос.Дата CustomAttributes)

        // *** End programmer edit section *** (ФормирРезПос.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРезПос.Дата Get start)

                // *** End programmer edit section *** (ФормирРезПос.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ФормирРезПос.Дата Get end)

                // *** End programmer edit section *** (ФормирРезПос.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРезПос.Дата Set start)

                // *** End programmer edit section *** (ФормирРезПос.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ФормирРезПос.Дата Set end)

                // *** End programmer edit section *** (ФормирРезПос.Дата Set end)
            }
        }
        
        /// <summary>
        /// НаличДеф.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРезПос.НаличДеф CustomAttributes)

        // *** End programmer edit section *** (ФормирРезПос.НаличДеф CustomAttributes)
        public virtual bool НаличДеф
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРезПос.НаличДеф Get start)

                // *** End programmer edit section *** (ФормирРезПос.НаличДеф Get start)
                bool result = this.fНаличДеф;
                // *** Start programmer edit section *** (ФормирРезПос.НаличДеф Get end)

                // *** End programmer edit section *** (ФормирРезПос.НаличДеф Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРезПос.НаличДеф Set start)

                // *** End programmer edit section *** (ФормирРезПос.НаличДеф Set start)
                this.fНаличДеф = value;
                // *** Start programmer edit section *** (ФормирРезПос.НаличДеф Set end)

                // *** End programmer edit section *** (ФормирРезПос.НаличДеф Set end)
            }
        }
        
        /// <summary>
        /// СтатусЗаказа.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРезПос.СтатусЗаказа CustomAttributes)

        // *** End programmer edit section *** (ФормирРезПос.СтатусЗаказа CustomAttributes)
        public virtual IIS.Proba1.СтатусЗаказа СтатусЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРезПос.СтатусЗаказа Get start)

                // *** End programmer edit section *** (ФормирРезПос.СтатусЗаказа Get start)
                IIS.Proba1.СтатусЗаказа result = this.fСтатусЗаказа;
                // *** Start programmer edit section *** (ФормирРезПос.СтатусЗаказа Get end)

                // *** End programmer edit section *** (ФормирРезПос.СтатусЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРезПос.СтатусЗаказа Set start)

                // *** End programmer edit section *** (ФормирРезПос.СтатусЗаказа Set start)
                this.fСтатусЗаказа = value;
                // *** Start programmer edit section *** (ФормирРезПос.СтатусЗаказа Set end)

                // *** End programmer edit section *** (ФормирРезПос.СтатусЗаказа Set end)
            }
        }
        
        /// <summary>
        /// УдовлКл.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРезПос.УдовлКл CustomAttributes)

        // *** End programmer edit section *** (ФормирРезПос.УдовлКл CustomAttributes)
        public virtual IIS.Proba1.УдовлКл УдовлКл
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРезПос.УдовлКл Get start)

                // *** End programmer edit section *** (ФормирРезПос.УдовлКл Get start)
                IIS.Proba1.УдовлКл result = this.fУдовлКл;
                // *** Start programmer edit section *** (ФормирРезПос.УдовлКл Get end)

                // *** End programmer edit section *** (ФормирРезПос.УдовлКл Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРезПос.УдовлКл Set start)

                // *** End programmer edit section *** (ФормирРезПос.УдовлКл Set start)
                this.fУдовлКл = value;
                // *** Start programmer edit section *** (ФормирРезПос.УдовлКл Set end)

                // *** End programmer edit section *** (ФормирРезПос.УдовлКл Set end)
            }
        }
        
        /// <summary>
        /// Формир рез пос.
        /// </summary>
        // *** Start programmer edit section *** (ФормирРезПос.ФормирРаспр CustomAttributes)

        // *** End programmer edit section *** (ФормирРезПос.ФормирРаспр CustomAttributes)
        [PropertyStorage(new string[] {
                "ФормирРаспр"})]
        [NotNull()]
        public virtual IIS.Proba1.ФормирРаспр ФормирРаспр
        {
            get
            {
                // *** Start programmer edit section *** (ФормирРезПос.ФормирРаспр Get start)

                // *** End programmer edit section *** (ФормирРезПос.ФормирРаспр Get start)
                IIS.Proba1.ФормирРаспр result = this.fФормирРаспр;
                // *** Start programmer edit section *** (ФормирРезПос.ФормирРаспр Get end)

                // *** End programmer edit section *** (ФормирРезПос.ФормирРаспр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирРезПос.ФормирРаспр Set start)

                // *** End programmer edit section *** (ФормирРезПос.ФормирРаспр Set start)
                this.fФормирРаспр = value;
                // *** Start programmer edit section *** (ФормирРезПос.ФормирРаспр Set end)

                // *** End programmer edit section *** (ФормирРезПос.ФормирРаспр Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ФормирРезПосE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормирРезПосE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормирРезПосE", typeof(IIS.Proba1.ФормирРезПос));
                }
            }
            
            /// <summary>
            /// "ФормирРезПосL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормирРезПосL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормирРезПосL", typeof(IIS.Proba1.ФормирРезПос));
                }
            }
        }
    }
}
